# comentarios se for rodar sem compose
server:
  port: 8080
jwt:
  secretKey: ""
google:
  clientId: ""
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db:3306/projeto
    username: root
    password: "123"
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  rabbitmq:
    host: rabbitmq #localhost
    port: 5672
    username: rabbitmq #guest
    password: rabbitmq #guest
