server:
  port: 8085

spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: rabbitmq
    password: rabbitmq
  mail:
    host: smtp.gmail.com
    port: 587
    username: "" # emailfrom, usado para enviar
    password: "" # password app key email
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
