server:
  port: 8088

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  mail:
    host: smtp.gmail.com
    port: 587
    username: projetointegracao45607@gmail.com # emailfrom, usado para
    password: "" # password app key email
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
